language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: d1QzO9CgkZMyZWJKsNgGaQR4bPN267H2JRE929n58gCPeid4cQOVUguSPaU2t7R/iEwWhF54QDoJ0Sx31qZK02GKFhoiebc8A2wHV7KWxb6F3G4TWbSYeqenp5EKfBeBvrscut0So/Q5NhBsFiFE9ipKW/MBtUWnTz6uQrywuRQcdznwfuP98oiuoT7hNC/5kHN6A5t5WhPfWxuE9TAsd47oU8pC5SHPD8LSUSVWsOcgAg1LM8Cxo4PnPi1gCSVFSz8m4OsgsTt8tFgqB40ZuAC+RrrZDVYMHsfk6R/VFBNr7IX01OV9sCrT4QAmno3cwM/FTTTF7Uloip5KLNV9w38oEX8n3lSdlLk9JAGKAqDBswq5FnJOZoY9vuOO8rhht0vzmrkUa3XFX/7bebBWbQcmXvKp2IHbJzz6sNK6P34+Z6ijv3Obu27z95xHydpMiOEekgef5jKufvkkFJ78ue7fbJ9gA6FkZkFQV9xTjkEMs+fLxCCAQCtKf5PIaPVdAlX81Yl5UyV3WajyoRv3niGQ7ES2hx7RtiHufYupGPE8NCIugI/jrUluKELhDvZnavK4GET9cA0h2bj/+W8rJ34UkJTLc5zMIuPuFfZoGlzOCQebkP0lEy6+EcNXV/Qo+47UzTcCzuiYVaPRA0/xcQ+nCJbE1DWMq5ZHKNUAM3c=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
