language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: HSAYt0tDv+/PJdwy1SDXHcW/7ef2pYOp5W86zH9q89zBGDXbPbwGlJmLNkaB64mMXgkCrQB+Hbp2igxH1p633eCpMBw/0WOJY9SnetWosVC2JMsOqsjKFUi8VNJjWliXU0/pDpQ6eXX0WW7NscxYODMaTMIPpLZCu40bJcDSysG9M4henWF4jZAUcxOEEYsB1b/0RoDNUAekNSXhy609CWBjFDAYgvNbPjxgLgyQs8mbAD4Z35OQIRUxZLpdPFBDeBDCoEX/E7aaBCwJmy4ycbruQYvqEMyz5ZpTeTLa+1fswYz3tHf4tcnjTG5kEPlEhA9xCZfWhYx37fWUGCauZsEEbRfL5AI6VLb6l4JrjtdbD3T7bTWwg8BUSMk/1UgnoVFpFHJXjQND9FSpPp62fN3D08ONzNgoRQ9sffix3nwhh93c01HNyZ+8o8h7LF3Oo0mlCJAgN/BbpZdhHI1BKIM9mACbPJVMwDqIlpqtKiy/ghjHnlE1psiZc/k3tIz3Pj17wycIFyP1JL6pPd8GbVTSR7EkhlGaJBe9Y72uyBnTtg0V06d8IqDyJa+G8D3eymAcP16vX6IWgXZmPuPxRvo6vZgIjw73kTh4c0zH/neqUt2eub9HdFHTK4LefkFShevlDlCqIVRa6H3QtgZCq0k08PPp3pNSvSPm1VTh8oI=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
