language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: fQPlXzUUcUKnoPKo0VOsxk+g51tVbwE+oq+Fv9vJvt8ApD47GYpS8jJRtc03OLd4GrPx/n65IAUGUZIBhY/PN40Mj4mjslq3GpQe3i3UtidRFJ4BQBYrkZe+EWq9kQ5o/Zaw5UAOc8K1yd0kVQOccAGb98VJiKSvEIhPaGVP2gg8LhIbm89agH1QZvrsJYYAD+xCluZFiEv13HYR7eel05XefpV8kFO3VGNMFR2/nF9mIOPdrIZ8eCG5X85kUe09su5C9qU39/XzgAUbjJgzCV+8LXWE0Zl/mrJ5Yj0IBhpFFPaTSFFeoK8E/kd7fPG615llOCDQdm8XI5Lvg8mm80AxBvR6+MEno+z7p/k24QWyiwCGxOsBiyFv5WaeKzfFHNuuqhTQQ5+taggupKswJokF7Qie//B35ktu1mADhUx+1/5RvUA3f9KdQH+YnHk4s1OZyLAcF7DNhudNLhtB64WHGG2xEV4KRNuSu+EC4a7APqam5gxlF1Rb0hqQr4tDz5WUl9o9/ITK56eJmh2CISGppB/5jSeZZwV0LZkWemuyOalf+QoUVXrN1PPZxt9aajY6yoNZTj3FRxt71z5lrhmWM69fd2ShdluV51fOUi0XaFtxn7Eow0gd+lBhXntjWVt+Z5dP/2C4cgQSPGBy/rbsKIw1uQ4VOMJRVmcfrHQ=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
